import { Open_Sans } from "next/font/google";
import { NextIntlClientProvider, useMessages } from "next-intl";

import "./globals.css";

const inter = Open_Sans({ subsets: ["latin", "cyrillic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const messages = useMessages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
